// Static catalog of "skills" — capabilities surfaced in the Apps browser.
// Each skill maps to a single backing model (fal.ai or pika:*). Skills with
// `comingSoon: true` show in the grid but cannot be launched yet. Skills
// with category "Hidden" are kept in the registry (so SKILL_BY_ID lookups
// from home/recipes/etc. still resolve) but do not appear in any tab.

import {
  Image as ImageIcon,
  Video as VideoIcon,
  Music as MusicIcon,
  Mic as MicIcon,
  Users as UsersIcon,
  Mountain as MountainIcon,
  Shirt as ShirtIcon,
  Sofa as SofaIcon,
  Sparkles as SparklesIcon,
  Type as TypeIcon,
  Camera as CameraIcon,
  Package as PackageIcon,
  Palette as PaletteIcon,
  Wand2 as Wand2Icon,
  Eraser as EraserIcon,
  ScanFace as ScanFaceIcon,
  Disc3 as Disc3Icon,
  Megaphone as MegaphoneIcon,
  Headphones as HeadphonesIcon,
  BookOpen as BookOpenIcon,
  Film as FilmIcon,
  Clapperboard as ClapperboardIcon,
  Zap as ZapIcon,
  Plus as PlusIcon,
  Maximize2 as ExpandIcon,
  Crop as CropIcon,
  Sun as SunIcon,
  Layers as LayersIcon,
  Paintbrush as PaintbrushIcon,
  Move3d as Move3dIcon,
  Trees as TreesIcon,
  PencilLine as PencilLineIcon,
  Scissors as ScissorsIcon,
  Subtitles as SubtitlesIcon,
  Languages as LanguagesIcon,
  AudioLines as AudioLinesIcon,
  CircleSlash2 as CircleSlashIcon,
  Rocket as RocketIcon,
  Bot as BotIcon,
  Cpu as CpuIcon,
  Flame as FlameIcon,
  Star as StarIcon,
  type LucideIcon,
} from "lucide-react";
import { Sneaker as PhosphorSneaker } from "@phosphor-icons/react";
import { createElement, forwardRef } from "react";

// Phosphor's Sneaker adapted to lucide's prop surface (size/className/etc.).
const SneakerIcon = forwardRef<SVGSVGElement, React.ComponentProps<LucideIcon>>(
  (props, ref) =>
    createElement(PhosphorSneaker, {
      ref,
      ...props,
      weight: "regular",
    } as never),
) as unknown as LucideIcon;
SneakerIcon.displayName = "SneakerIcon";

export type SkillKind = "image" | "video" | "audio" | "speech";

export type Skill = {
  id: string;
  label: string;
  description: string;
  category: string;
  kind: SkillKind;
  model: string; // backing model id (fal or pika:*)
  icon: LucideIcon;
  comingSoon?: boolean;
  featured?: boolean;
  /** Optional hero video URL shown on the app card when no full showcase exists. */
  heroVideoUrl?: string;
  /** Optional hero image URL for still-image models (rendered as <img>). */
  heroImageUrl?: string;
};

// ── Constants ───────────────────────────────────────────────────────
const NANO = "fal-ai/nano-banana";
const NANO_EDIT = "fal-ai/nano-banana/edit";
const FLUX_PRO = "fal-ai/flux-pro/v1.1";
const IDEO = "fal-ai/ideogram/v3";
const KLING_I2V = "fal-ai/kling-video/v2.1/standard/image-to-video";
const KLING_T2V = "fal-ai/kling-video/v2.1/master/text-to-video";
const LUMA = "fal-ai/luma-dream-machine/ray-2";
const MINIMAX = "fal-ai/minimax/video-01";
// CassetteAI apps live at `cassetteai/...` on fal, not under the `fal-ai/`
// namespace. Using `fal-ai/cassetteai/...` makes the queue API 404 with
// `Application "cassetteai" not found`.
const CASSETTE = "cassetteai/music-generator";
const STABLE_AUDIO = "fal-ai/stable-audio-25/text-to-audio";
const ELEVEN = "fal-ai/elevenlabs/tts/multilingual-v2";
const PIKA_I2V = "pika:image-to-video-v2";

const SOON = ""; // placeholder for unreleased models

// ── Hero media assets reused from the Pika API marketing page ──────
import pikaFramesOut from "@/assets/pika-api/frames_out.asset.json";
import pikaScenesOut from "@/assets/pika-api/scenes_out.asset.json";
import pikaI2v22Out from "@/assets/pika-api/i2v22_out.asset.json";
import pikaTurboI2vOut from "@/assets/pika-api/turbo_i2v_out.asset.json";
import pikaExplodeOut from "@/assets/pika-api/pkf_explode_out.asset.json";

// ── Hero media hosted on fal's public sample bucket ────────────────
const FAL_SAMPLE_KLING_V25 =
  "https://storage.googleapis.com/falserverless/model_tests/kling/kling-v2.5-turbo-pro-image-to-video-output.mp4";
const FAL_SAMPLE_WAN_25 =
  "https://storage.googleapis.com/falserverless/example_outputs/wan-25-i2v-output.mp4";
const FAL_SAMPLE_SEEDREAM_4 =
  "https://storage.googleapis.com/falserverless/example_outputs/seedream4_t2i_output.png";
const FAL_SAMPLE_NANO_BANANA_2 =
  "https://storage.googleapis.com/falserverless/example_outputs/nano-banana-2-t2i-output.png";

export const SKILLS: Skill[] = [
  // ── Models ──────────────────────────────────────────────────────
  {
    id: "model-seedance-2",
    label: "Seedance 2.0",
    description: "ByteDance's flagship text-to-video model — cinematic motion and prompt fidelity.",
    category: "Models",
    kind: "video",
    model: "bytedance/seedance-2.0/text-to-video",
    icon: RocketIcon,
    featured: true,
  },
  {
    id: "model-seedance-2-mini",
    label: "Seedance 2.0 Mini",
    description: "Faster, lower-cost Seedance 2.0 — same ByteDance engine tuned for speed and volume.",
    category: "Models",
    kind: "video",
    model: "bytedance/seedance-2.0/mini/text-to-video",
    icon: RocketIcon,
    featured: true,
  },
  {
    id: "model-seedream",
    label: "Seedream",
    description: "High-fidelity text-to-image from ByteDance.",
    category: "Models",
    kind: "image",
    model: "fal-ai/bytedance/seedream/v4/text-to-image",
    icon: SparklesIcon,
    heroImageUrl: FAL_SAMPLE_SEEDREAM_4,
  },
  {
    id: "model-grok-imagine",
    label: "Grok Imagine",
    description: "xAI's image generation model.",
    category: "Models",
    kind: "image",
    model: SOON,
    icon: BotIcon,
    comingSoon: true,
  },
  {
    id: "model-kling-3",
    label: "Kling 3.0",
    description: "Latest Kling video model — best-in-class motion and dynamics.",
    category: "Models",
    kind: "video",
    model: "fal-ai/kling-video/v2.5-turbo/pro/text-to-video",
    icon: VideoIcon,
    heroVideoUrl: FAL_SAMPLE_KLING_V25,
  },
  {
    id: "model-kling-3-motion",
    label: "Kling 3.0 Motion Control",
    description: "Kling 3.0 with explicit camera and motion controls.",
    category: "Models",
    kind: "video",
    model: "fal-ai/kling-video/v3/pro/motion-control",
    icon: Move3dIcon,
    heroVideoUrl: FAL_SAMPLE_KLING_V25,
  },
  {
    id: "model-grok-imagine-15",
    label: "Grok Imagine 1.5",
    description: "Next-gen Grok Imagine with better composition.",
    category: "Models",
    kind: "image",
    model: SOON,
    icon: BotIcon,
    comingSoon: true,
  },
  {
    id: "model-google-omni",
    label: "Google Omni",
    description: "Google's multimodal generative model.",
    category: "Models",
    kind: "image",
    model: SOON,
    icon: CpuIcon,
    comingSoon: true,
  },
  {
    id: "model-wan-27",
    label: "Wan 2.7",
    description: "Wan v2.7 — large open video model.",
    category: "Models",
    kind: "video",
    model: "fal-ai/wan-25-preview/text-to-video",
    icon: VideoIcon,
    heroVideoUrl: FAL_SAMPLE_WAN_25,
  },
  {
    id: "model-veo-31-lite",
    label: "Google Veo 3 Fast",
    description: "Google's Veo 3 in faster, lower-cost mode — text-to-video with native audio.",
    category: "Models",
    kind: "video",
    model: "fal-ai/veo3/fast",
    icon: FilmIcon,
  },
  {
    id: "model-veo-3",
    label: "Google Veo 3",
    description: "Google's flagship Veo 3 — cinematic text-to-video with native audio generation.",
    category: "Models",
    kind: "video",
    model: "fal-ai/veo3",
    icon: FilmIcon,
    featured: false,
  },
  {
    id: "model-veo-3-i2v",
    label: "Google Veo 3 — Image to Video",
    description: "Animate any still image with Google Veo 3, complete with native audio.",
    category: "Models",
    kind: "video",
    model: "fal-ai/veo3/image-to-video",
    icon: FilmIcon,
  },
  {
    id: "model-pika-i2v-fal",
    label: "Pika v2.2 — Image to Video",
    description: "Pika 2.2 image-to-video via fal — sharper visuals, up to 1080p.",
    category: "Models",
    kind: "video",
    model: "fal-ai/pika/v2.2/image-to-video",
    icon: ZapIcon,
  },
  {
    id: "model-gpt-image-2",
    label: "GPT Image 2",
    description: "OpenAI's GPT Image 2 model.",
    category: "Models",
    kind: "image",
    model: "openai/gpt-image-2",
    icon: ImageIcon,
  },
  {
    id: "model-nano-banana-2",
    label: "Nano Banana 2 / Pro",
    description: "Next-gen Nano Banana — bigger, sharper, more prompt-faithful.",
    category: "Models",
    kind: "image",
    model: "fal-ai/nano-banana-2",
    icon: ImageIcon,
    heroImageUrl: FAL_SAMPLE_NANO_BANANA_2,
  },
  {
    id: "model-pika-keyframe",
    label: "Pika 2.5 Keyframe",
    description: "Generate video from start/end keyframes with Pika 2.5.",
    category: "Models",
    kind: "video",
    model: "fal-ai/pika/v2.2/pikaframes",
    icon: FilmIcon,
    heroVideoUrl: pikaFramesOut.url,
  },
  {
    id: "app-animate-photo",
    label: "Pika 2.5 Image to Video",
    description: "Pika's flagship image-to-video — animate any still with motion and atmosphere.",
    category: "Models",
    kind: "video",
    model: PIKA_I2V,
    icon: ZapIcon,
    featured: false,
  },
  {
    id: "model-pika-t2v",
    label: "Pika 2.2 Text to Video",
    description: "Pika 2.2 text-to-video — generate clips straight from a prompt, up to 1080p.",
    category: "Models",
    kind: "video",
    model: "fal-ai/pika/v2.2/text-to-video",
    icon: VideoIcon,
  },
  {
    id: "model-pika-performance",
    label: "Pika Turbo (Image to Video)",
    description: "Pika v2 Turbo — up to 3× faster image-to-video for rapid iteration.",
    category: "Models",
    kind: "video",
    model: "fal-ai/pika/v2/turbo/image-to-video",
    icon: FlameIcon,
  },
  {
    id: "model-pikaddition",
    label: "Pikaddition",
    description: "Drop new elements into an existing video clip.",
    category: "Models",
    kind: "video",
    model: "fal-ai/pika/v2/pikadditions",
    icon: PlusIcon,
    heroVideoUrl: pikaI2v22Out.url,
    comingSoon: true,
  },
  {
    id: "model-pikaswap",
    label: "Pikaswap",
    description: "Swap subjects, objects, or backgrounds inside a video.",
    category: "Models",
    kind: "video",
    model: "fal-ai/pika/v2/pikaswaps",
    icon: Wand2Icon,
    heroVideoUrl: pikaTurboI2vOut.url,
  },
  {
    id: "model-pikascenes",
    label: "Pikascenes",
    description: "Stitch multiple scenes together into a coherent video.",
    category: "Models",
    kind: "video",
    model: "fal-ai/pika/v2.2/pikascenes",
    icon: LayersIcon,
    heroVideoUrl: pikaScenesOut.url,
  },
  {
    id: "model-pikatwists",
    label: "Pikatwists",
    description: "Add surprising creative twists and remixes to your clips.",
    category: "Models",
    kind: "video",
    model: "fal-ai/pika/v2.2/pikatwists",
    icon: SparklesIcon,
    heroVideoUrl: pikaExplodeOut.url,
    comingSoon: true,
  },

  // ── Create Media ────────────────────────────────────────────────
  {
    id: "app-create-image",
    label: "Create Image",
    description: "Generate an image from a prompt — pick any image model.",
    category: "Create Media",
    kind: "image",
    model: NANO,
    icon: ImageIcon,
  },
  {
    id: "app-create-video",
    label: "Create Video",
    description: "Generate a video from a prompt — text-to-video or image-to-video.",
    category: "Create Media",
    kind: "video",
    model: KLING_T2V,
    icon: VideoIcon,
  },
  {
    id: "app-create-speech",
    label: "Create Audio / Speech",
    description: "Synthesize speech and voiceover from any text.",
    category: "Create Media",
    kind: "speech",
    model: ELEVEN,
    icon: MicIcon,
  },
  {
    id: "app-create-music",
    label: "Create Music",
    description: "Generate original music beds and instrumentals.",
    category: "Create Media",
    kind: "audio",
    model: CASSETTE,
    icon: MusicIcon,
  },
  {
    id: "app-create-sfx",
    label: "Create SFX",
    description: "Generate one-shot sound effects from a description.",
    category: "Create Media",
    kind: "audio",
    model: STABLE_AUDIO,
    icon: ZapIcon,
  },
  {
    id: "app-camera-control-video",
    label: "Camera Control to Video",
    description: "Direct your shot with explicit camera moves — push, pan, orbit, dolly.",
    category: "Create Media",
    kind: "video",
    model: SOON,
    icon: CameraIcon,
    comingSoon: true,
  },

  // ── Image Apps ──────────────────────────────────────────────────
  {
    id: "app-inpaint",
    label: "Inpaint",
    description: "Mask a region and let the model fill it in seamlessly.",
    category: "Image Apps",
    kind: "image",
    model: SOON,
    icon: PaintbrushIcon,
    comingSoon: true,
  },
  {
    id: "app-cinematic-camera",
    label: "Cinematic Camera",
    description: "Restage any photo with cinematic camera, lens, and lighting.",
    category: "Image Apps",
    kind: "image",
    model: SOON,
    icon: CameraIcon,
    comingSoon: true,
  },
  {
    id: "app-image-upscale",
    label: "Image Upscale",
    description: "Sharpen and upscale images to higher resolution.",
    category: "Image Apps",
    kind: "image",
    model: SOON,
    icon: ExpandIcon,
    comingSoon: true,
  },
  {
    id: "app-image-expand",
    label: "Image Expand",
    description: "Outpaint beyond the edges of an existing image.",
    category: "Image Apps",
    kind: "image",
    model: SOON,
    icon: CropIcon,
    comingSoon: true,
  },
  {
    id: "app-character-creator",
    label: "Character Creator",
    description: "Design a consistent character — upload or generate, then pick style, angle, and expression. Always on a clean white background.",
    category: "Image Apps",
    kind: "image",
    model: NANO,
    icon: ScanFaceIcon,
    featured: true,
    heroVideoUrl: "https://cdn.openart.ai/openart-strapi-assets/Hero_8814511bf0_1080p/Hero_8814511bf0_1080p.mp4",
  },
  {
    id: "app-relight",
    label: "Relight",
    description: "Re-light a photo — change time of day, light direction, mood.",
    category: "Image Apps",
    kind: "image",
    model: SOON,
    icon: SunIcon,
    comingSoon: true,
  },
  {
    id: "app-photodump",
    label: "Photodump",
    description: "Generate a cohesive set of casual photos in one go.",
    category: "Image Apps",
    kind: "image",
    model: SOON,
    icon: LayersIcon,
    comingSoon: true,
  },
  {
    id: "app-moodboard",
    label: "Moodboard",
    description: "Compose a moodboard of reference images from a brief.",
    category: "Image Apps",
    kind: "image",
    model: SOON,
    icon: PaletteIcon,
    comingSoon: true,
  },

  // ── Video Apps ──────────────────────────────────────────────────
  {
    id: "app-motion-control",
    label: "Motion Control",
    description: "Direct subject and camera motion with precise controls.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: Move3dIcon,
    comingSoon: true,
  },
  {
    id: "app-lipsync-studio",
    label: "Lipsync Studio",
    description: "Sync any face to any voice — drop in a portrait and audio, get a talking clip.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: MicIcon,
    comingSoon: true,
  },
  {
    id: "app-multishot-video",
    label: "Multi-shot Video",
    description: "Compose multi-shot videos with consistent characters and style.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: ClapperboardIcon,
    comingSoon: true,
  },
  {
    id: "app-edit-video",
    label: "Edit Video",
    description: "Edit a clip with prompts — re-cut, restyle, retouch.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: Wand2Icon,
    comingSoon: true,
  },
  {
    id: "app-upscale-video",
    label: "Upscale Video",
    description: "Upscale and sharpen video to higher resolution.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: ExpandIcon,
    comingSoon: true,
  },
  {
    id: "app-dubbing",
    label: "Dubbing / Translation",
    description: "Re-dub a clip into another language with lipsync.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: LanguagesIcon,
    comingSoon: true,
  },
  {
    id: "app-add-caption",
    label: "Add Caption",
    description: "Add styled captions and subtitles to your video.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: SubtitlesIcon,
    comingSoon: true,
  },
  {
    id: "app-clipping",
    label: "Clipping",
    description: "Auto-clip long videos into shareable highlights.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: ScissorsIcon,
    comingSoon: true,
  },
  {
    id: "app-bg-remover-video",
    label: "Background Remover / Editor",
    description: "Remove or replace the background in any video.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: CircleSlashIcon,
    comingSoon: true,
  },
  {
    id: "app-color-grading",
    label: "Color Grading",
    description: "Apply cinematic color grades to your video.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: PaletteIcon,
    comingSoon: true,
  },
  {
    id: "app-expand-video",
    label: "Expand Video",
    description: "Extend a video clip beyond its original duration.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: ExpandIcon,
    comingSoon: true,
  },
  {
    id: "app-audio-tools",
    label: "Audio Tools",
    description: "Clean, enhance, and re-mix the audio track of a video.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: AudioLinesIcon,
    comingSoon: true,
  },
  {
    id: "app-translation",
    label: "Translation",
    description: "Translate the spoken track of a video into another language.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: LanguagesIcon,
    comingSoon: true,
  },
  {
    id: "app-change-voice",
    label: "Change Voice",
    description: "Swap the voice in a clip while preserving timing.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: MicIcon,
    comingSoon: true,
  },
  {
    id: "app-voiceover",
    label: "Voiceover",
    description: "Lay a generated voiceover over any video.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: MicIcon,
    comingSoon: true,
  },
  {
    id: "app-relight-video",
    label: "Relight Video",
    description: "Re-light any video clip — change time of day, light direction, and mood.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: SunIcon,
    comingSoon: true,
  },
  {
    id: "app-create-environment",
    label: "Create Environment",
    description: "Build a scene or world from a brief — locations, sets, and backdrops on demand.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: TreesIcon,
    comingSoon: true,
  },
  {
    id: "app-script-writer",
    label: "Script Writer",
    description: "Turn a premise into a scene-by-scene script with dialog and action.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: PencilLineIcon,
    comingSoon: true,
  },
  {
    id: "app-shot-list",
    label: "Shot List",
    description: "Choreograph a shot list — lens, framing, and movement for every beat.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: ClapperboardIcon,
    comingSoon: true,
  },
  {
    id: "app-art-director",
    label: "Art Director",
    description: "Generate a style bible and creative direction for a video production.",
    category: "Video Apps",
    kind: "video",
    model: SOON,
    icon: Wand2Icon,
    comingSoon: true,
  },

  // ── Templates ───────────────────────────────────────────────────
  {
    id: "app-world-cup-2026",
    label: "World Cup 2026 Video",
    description: "Star in your own FIFA World Cup 2026 broadcast — upload a selfie, pick your team and your moment, and we'll cut you into the live TV feed.",
    category: "Templates",
    kind: "video",
    model: "bytedance/seedance-2.0/reference-to-video",
    icon: StarIcon,
    featured: true,
  },
  {
    id: "app-anime-world-cup-2026",
    label: "Anime World Cup 2026",
    description: "Become an original anime character of the FIFA World Cup 2026 — upload a selfie, pick your team and an anime genre, and let Seedance invent a wild ~15s scene.",
    category: "Templates",
    kind: "video",
    model: "bytedance/seedance-2.0/reference-to-video",
    icon: SparklesIcon,
    featured: true,
  },
  {
    id: "app-time-tourist-v2",
    label: "Time Tourist",
    description: "Turn a selfie into a first-person historical travel vlog — Ancient Rome, Edo Japan, Wild West and more. Selfie → Seedance 2.0, 9:16, 15s.",
    category: "Templates",
    kind: "video",
    model: "bytedance/seedance-2.0/reference-to-video",
    icon: RocketIcon,
    featured: true,
  },
  {
    id: "app-pikaffects",
    label: "Pikaffects",
    description: "One-tap viral effects — cake, crumble, explode, levitate, peel, squish, tear.",
    category: "Templates",
    kind: "video",
    model: SOON,
    icon: SparklesIcon,
    comingSoon: true,
    featured: false,
  },
  {
    id: "app-headshot-studio",
    label: "Headshot Studio",
    description: "Turn a casual selfie into a polished, photoreal LinkedIn-grade portrait.",
    category: "Templates",
    kind: "image",
    model: FLUX_PRO,
    icon: ScanFaceIcon,
    featured: false,
  },
  {
    id: "app-product-shot",
    label: "Product Shot",
    description: "Studio-grade product photography from a plain catalog image — any lighting, any set.",
    category: "Templates",
    kind: "image",
    model: FLUX_PRO,
    icon: PackageIcon,
    featured: false,
  },
  {
    id: "app-special-product-ad",
    label: "Product Ad",
    description: "Multi-shot product ad: write a brief, get a cinematic concept, render it with Seedance 2.0 — sound included.",
    category: "Templates",
    kind: "video",
    model: "bytedance/seedance-2.0/text-to-video",
    icon: SneakerIcon,
    featured: true,
  },
  {
    id: "app-from-url",
    label: "From URL / Product Photo",
    description: "Drop a product URL or photo — get a polished ad-ready render.",
    category: "Templates",
    kind: "image",
    model: SOON,
    icon: PackageIcon,
    comingSoon: true,
    featured: false,
  },
  {
    id: "app-short-film",
    label: "Short Film",
    description: "Multi-shot short film: write a logline, design character + environment, draft a storyboard, render it with sound.",
    category: "Templates",
    kind: "video",
    model: "bytedance/seedance-2.0/text-to-video",
    icon: FilmIcon,
    featured: true,
  },
  {
    id: "app-ugc-ads",
    label: "UGC Ads",
    description: "Creator-style ad reads for social — talking-head UGC at scale.",
    category: "Templates",
    kind: "video",
    model: SOON,
    icon: MegaphoneIcon,
    comingSoon: true,
    featured: true,
  },
  {
    id: "app-commercial",
    label: "Commercial",
    description: "Polished commercial spots from a brand brief.",
    category: "Templates",
    kind: "video",
    model: SOON,
    icon: ClapperboardIcon,
    comingSoon: true,
    featured: true,
  },
  {
    id: "app-short-drama",
    label: "Short Drama",
    description: "Vertical short drama series — multi-shot, multi-scene.",
    category: "Templates",
    kind: "video",
    model: SOON,
    icon: FilmIcon,
    comingSoon: true,
    featured: true,
  },
  {
    id: "app-product-marketing-video",
    label: "Product Marketing Video",
    description: "Demo-loop + voiceover product marketing video in one pass.",
    category: "Templates",
    kind: "video",
    model: SOON,
    icon: PackageIcon,
    comingSoon: true,
    featured: true,
  },

  // ── Audio Apps (real fal audio/music/sfx endpoints) ─────────────
  {
    id: "audio-elevenlabs-music",
    label: "ElevenLabs Music",
    description: "Studio-grade text-to-music with fine controls — vocals, arrangement, genre.",
    category: "Audio Apps",
    kind: "audio",
    model: "fal-ai/elevenlabs/music",
    icon: MusicIcon,
    featured: false,
  },
  {
    id: "audio-minimax-music-26",
    label: "MiniMax Music 2.6",
    description: "Complete tracks with singing, backing music, and arrangement from lyrics + a style prompt.",
    category: "Audio Apps",
    kind: "audio",
    model: "fal-ai/minimax-music/v2.6",
    icon: Disc3Icon,
    featured: false,
  },
  {
    id: "audio-stable",
    label: "Stable Audio 2.5",
    description: "High-quality original music and sound design from Stability AI.",
    category: "Audio Apps",
    kind: "audio",
    model: STABLE_AUDIO,
    icon: HeadphonesIcon,
  },
  {
    id: "audio-cassette",
    label: "Cassette Music",
    description: "Lightning-fast 44.1 kHz stereo instrumentals — 30s sample in under 2s.",
    category: "Audio Apps",
    kind: "audio",
    model: CASSETTE,
    icon: MusicIcon,
  },
  {
    id: "audio-minimax-music-v2",
    label: "MiniMax Music 2.0",
    description: "Diverse text-to-music with vocals — earlier MiniMax music model.",
    category: "Audio Apps",
    kind: "audio",
    model: "fal-ai/minimax-music/v2",
    icon: MusicIcon,
  },

  // ── SFX Apps ────────────────────────────────────────────────────
  {
    id: "audio-elevenlabs-sfx",
    label: "ElevenLabs Sound Effects",
    description: "Hyper-real one-shot SFX from a text prompt — whooshes, impacts, ambiences.",
    category: "Audio Apps",
    kind: "audio",
    model: "fal-ai/elevenlabs/sound-effects",
    icon: ZapIcon,
    featured: false,
  },
  {
    id: "audio-cassette-sfx",
    label: "Cassette SFX",
    description: "Fast custom sound effects from a description — 44.1 kHz stereo.",
    category: "Audio Apps",
    kind: "audio",
    model: "cassetteai/sound-effects-generator",
    icon: ZapIcon,
  },
  {
    id: "audio-beatoven-sfx",
    label: "Beatoven SFX",
    description: "Professional sound effects — animals, vehicles, nature, sci-fi, otherworldly.",
    category: "Audio Apps",
    kind: "audio",
    model: "beatoven/sound-effect-generation",
    icon: AudioLinesIcon,
  },
  {
    id: "audio-seed-audio",
    label: "ByteDance Seed-Audio 1.0",
    description: "ByteDance's Seed-Audio — high-quality music and sound generation from a text prompt.",
    category: "Audio Apps",
    kind: "audio",
    model: "bytedance/seed-audio-1.0",
    icon: MusicIcon,
  },

  // ── Voice Apps (real fal TTS endpoints) ─────────────────────────
  {
    id: "speech-elevenlabs",
    label: "ElevenLabs Multilingual v2",
    description: "Studio-grade voiceover in 29 languages and dozens of voices.",
    category: "Voice Apps",
    kind: "speech",
    model: ELEVEN,
    icon: MicIcon,
    featured: false,
  },
  {
    id: "speech-elevenlabs-turbo",
    label: "ElevenLabs Turbo v2.5",
    description: "Low-latency ElevenLabs TTS — same quality, faster generation.",
    category: "Voice Apps",
    kind: "speech",
    model: "fal-ai/elevenlabs/tts/turbo-v2.5",
    icon: ZapIcon,
  },
  {
    id: "speech-minimax-hd",
    label: "MiniMax Speech 02 HD",
    description: "High-definition TTS with rich, expressive voices.",
    category: "Voice Apps",
    kind: "speech",
    model: "fal-ai/minimax/speech-02-hd",
    icon: MicIcon,
    featured: false,
  },
  {
    id: "speech-minimax-turbo",
    label: "MiniMax Speech 02 Turbo",
    description: "Fast MiniMax TTS — lower latency, same voice library.",
    category: "Voice Apps",
    kind: "speech",
    model: "fal-ai/minimax/speech-02-turbo",
    icon: ZapIcon,
  },
  {
    id: "speech-chatterbox",
    label: "Chatterbox TTS",
    description: "Expressive, character-forward TTS from Resemble AI — great for games and memes.",
    category: "Voice Apps",
    kind: "speech",
    model: "fal-ai/chatterbox/text-to-speech",
    icon: BotIcon,
  },
  {
    id: "speech-inworld",
    label: "Inworld TTS 1.5 Max",
    description: "Inworld's flagship TTS — natural, character-driven delivery.",
    category: "Voice Apps",
    kind: "speech",
    model: "fal-ai/inworld-tts",
    icon: MicIcon,
  },
  {
    id: "speech-seed-tts",
    label: "ByteDance Seed-Speech TTS v2",
    description: "ByteDance Seed-Speech — expressive, natural-sounding text-to-speech.",
    category: "Voice Apps",
    kind: "speech",
    model: "fal-ai/bytedance/seed-speech/tts/v2",
    icon: MicIcon,
  },

  // ── Hidden (kept for back-references; not shown in any tab) ─────
  {
    id: "app-create",
    label: "Create",
    description: "Direct prompt → media in any modality.",
    category: "Hidden",
    kind: "image",
    model: NANO,
    icon: SparklesIcon,
  },
  {
    id: "app-pika-lipsync",
    label: "Talking Head Studio",
    description: "Upload a face, type or upload audio, and get a talking-head clip with synced lips.",
    category: "Video Apps",
    kind: "video",
    model: "fal-ai/infinitalk",
    icon: MicIcon,
    featured: true,
  },
  { id: "app-character-swap", label: "Character Swap", description: "Drop a new character into any scene.", category: "Hidden", kind: "image", model: NANO_EDIT, icon: UsersIcon },
  { id: "app-background-swap", label: "Background Swap", description: "Send your subject anywhere.", category: "Hidden", kind: "image", model: NANO_EDIT, icon: MountainIcon },
  { id: "app-outfit-try-on", label: "Virtual Try-On", description: "Restyle a person in new clothing.", category: "Hidden", kind: "image", model: NANO_EDIT, icon: ShirtIcon },
  { id: "app-room-redesign", label: "Room Re-Designer", description: "Re-decorate an interior.", category: "Hidden", kind: "image", model: NANO_EDIT, icon: SofaIcon },
  { id: "app-glow-up", label: "Style Glow-Up", description: "Apply a cohesive look.", category: "Hidden", kind: "image", model: NANO_EDIT, icon: SparklesIcon },
  { id: "app-object-remove", label: "Cleanup & Remove", description: "Erase distractions.", category: "Hidden", kind: "image", model: NANO_EDIT, icon: EraserIcon },
  { id: "app-pet-portrait", label: "Pet Hero Portrait", description: "Your pet re-imagined.", category: "Hidden", kind: "image", model: FLUX_PRO, icon: PaletteIcon },
  { id: "app-poster-maker", label: "Poster Maker", description: "Event posters with typography.", category: "Hidden", kind: "image", model: IDEO, icon: TypeIcon },
  { id: "app-logo-mockup", label: "Logo Mockup", description: "Logo on surfaces.", category: "Hidden", kind: "image", model: NANO_EDIT, icon: Wand2Icon },
  { id: "app-album-cover", label: "Album Cover Art", description: "Square cover art.", category: "Hidden", kind: "image", model: IDEO, icon: Disc3Icon },
  { id: "app-ad-creative", label: "Ad Creative", description: "Social ad creative.", category: "Hidden", kind: "image", model: IDEO, icon: MegaphoneIcon },
  { id: "app-storyboard-frames", label: "Storyboard Frames", description: "Rapid keyframes.", category: "Hidden", kind: "image", model: "fal-ai/flux/schnell", icon: CameraIcon },
  { id: "app-cinematic-broll", label: "Cinematic B-Roll", description: "Filmic clips.", category: "Hidden", kind: "video", model: LUMA, icon: FilmIcon },
  { id: "app-music-video-clip", label: "Music Video Clip", description: "Short t2v clips.", category: "Hidden", kind: "video", model: KLING_T2V, icon: ClapperboardIcon },
  { id: "app-product-demo-loop", label: "Product Demo Loop", description: "Looping product clip.", category: "Hidden", kind: "video", model: KLING_I2V, icon: PackageIcon },
  { id: "app-trailer-snippet", label: "Trailer Snippet", description: "Cinematic teaser shot.", category: "Hidden", kind: "video", model: MINIMAX, icon: FilmIcon },
  { id: "image-nano-banana", label: "Nano Banana", description: "Fast, vivid text-to-image — great for moodboards and ideation.", category: "Models", kind: "image", model: NANO, icon: ImageIcon },
  { id: "image-nano-banana-edit", label: "Nano Banana Edit", description: "Edit or remix existing images while preserving identity.", category: "Models", kind: "image", model: NANO_EDIT, icon: ImageIcon },
  { id: "image-flux-schnell", label: "Flux Schnell", description: "Snappy Flux variant — high quality at low latency.", category: "Models", kind: "image", model: "fal-ai/flux/schnell", icon: ImageIcon },
  { id: "image-flux-pro", label: "Flux Pro 1.1", description: "Top-tier photoreal Flux — slower, premium fidelity.", category: "Models", kind: "image", model: FLUX_PRO, icon: ImageIcon },
  { id: "image-ideogram", label: "Ideogram v3", description: "Best-in-class for text-in-image, posters, and typography.", category: "Models", kind: "image", model: IDEO, icon: ImageIcon },
  { id: "video-kling-i2v", label: "Kling 2.1 — Image to Video", description: "Animate a still image with motion direction.", category: "Models", kind: "video", model: KLING_I2V, icon: VideoIcon },
  { id: "video-kling-t2v", label: "Kling 2.1 — Text to Video", description: "Generate a short clip from a written description.", category: "Models", kind: "video", model: KLING_T2V, icon: VideoIcon },
  { id: "video-luma", label: "Luma Dream Machine Ray 2", description: "Cinematic, dreamy motion — great for vibes and montages.", category: "Models", kind: "video", model: LUMA, icon: VideoIcon },
  { id: "video-minimax", label: "MiniMax Video 01", description: "Fast text-to-video with crisp subjects.", category: "Models", kind: "video", model: MINIMAX, icon: VideoIcon },
];

// Tag a noop reference to StarIcon to keep optional icons available for
// future Models entries without triggering unused-import warnings.
void StarIcon;

export const SKILL_BY_ID: Record<string, Skill> = Object.fromEntries(
  SKILLS.map((s) => [s.id, s]),
);

export const SKILL_BY_MODEL: Record<string, Skill> = Object.fromEntries(
  SKILLS.filter((s) => s.model).map((s) => [s.model, s]),
);

export const SKILL_CATEGORIES = Array.from(
  new Set(SKILLS.map((s) => s.category)),
);

export const SKILLS_BY_KIND = (kind: SkillKind): Skill[] =>
  SKILLS.filter((s) => s.kind === kind && !s.comingSoon);

export const DEFAULT_MODEL_BY_KIND: Record<SkillKind, string> = {
  image: NANO,
  video: KLING_T2V,
  audio: CASSETTE,
  speech: ELEVEN,
};

export type StudioMode = "agent" | "director-v2" | SkillKind;

export const STUDIO_MODES: { id: StudioMode; label: string }[] = [
  { id: "agent", label: "Agent" },
  { id: "director-v2", label: "Director (V3)" },
  { id: "image", label: "Image" },
  { id: "video", label: "Video" },
  { id: "audio", label: "Music" },
  { id: "speech", label: "Speech" },
];
