// Agent v3.1 → v6 — flat catalog of apps the agent can route the user into.
//
// Each app is now authored as a Skill pack under `src/agent/skills/<id>/`
// (skill.md + typed manifest). This file is the compatibility facade the
// legacy runtime (chat.ts, skills/registry.ts, etc.) still imports:
// `APP_REGISTRY`, `APP_BY_ID`, `renderAppPlaybook`, and
// `renderAppCatalogForPrompt` are derived on demand from the skill packs.
//
// To add a new app, DO NOT edit this file. Create a folder under
// src/agent/skills/<id>/ (see src/agent/skills/_registry.ts) — the entry
// shows up here automatically.

import { ALL_SKILLS, findSkillByAppId } from "@/agent/skills/_registry";
import type { SkillPack, SkillStep, StepInput as SkillStepInput } from "@/agent/skills/types";

export type StepInput = SkillStepInput;

export type AppStep = {
  id: string;
  intent: string;
  inputs: StepInput[];
  notes?: string;
};

export type AppEntry = {
  id: string;
  label: string;
  kind: "wizard" | "model";
  oneLiner: string;
  model?: string;
  mode?: "image" | "video" | "audio" | "speech";
  steps?: AppStep[];
};

function skillToAppEntry(s: SkillPack): AppEntry | null {
  // Meta-skills (SKL_CREATE_SKILL) don't ship as wizard/model apps yet.
  if (s.kind !== "wizard" && s.kind !== "model") return null;
  const steps: AppStep[] | undefined = s.steps?.map((st: SkillStep) => ({
    id: st.id,
    intent: st.intent,
    inputs: st.inputs,
    notes: st.notes,
  }));
  return {
    id: s.appId,
    label: s.label,
    kind: s.kind,
    oneLiner: s.oneLiner,
    model: s.model,
    mode: s.mode,
    steps,
  };
}

export const APP_REGISTRY: AppEntry[] = ALL_SKILLS.map(skillToAppEntry).filter(
  (a): a is AppEntry => a !== null,
);

export const APP_BY_ID: Record<string, AppEntry> = Object.fromEntries(
  APP_REGISTRY.map((a) => [a.id, a]),
);

function renderInput(i: StepInput): string {
  switch (i.kind) {
    case "upload":
      return `upload(${i.key}) "${i.label}" accepts=${i.accepts}`;
    case "url":
      return `url(${i.key}) "${i.label}"`;
    case "text":
      return `text(${i.key}) "${i.label}"${i.long ? " [long]" : ""}`;
    case "choice":
      return `choice(${i.key}) "${i.label}" [${i.options.join(" | ")}]${i.multi ? " multi" : ""}`;
    case "character":
      return `character-picker(${i.key}) "${i.label}"${i.multi ? " multi" : ""} — supports "Create new" → Character Creator inline`;
    case "environment":
      return `environment-picker(${i.key}) "${i.label}"`;
    case "voice":
      return `voice-picker(${i.key}) "${i.label}"`;
    case "asset-picker":
      return `library-picker(${i.key}) "${i.label}" kinds=${i.mediaKinds.join(",")}`;
  }
}

/**
 * Full playbook for ONE app — injected only when that app is selected (or
 * fetched on demand via the get_app_playbook tool). Prefers the pack's
 * hand-authored skill.md; falls back to a rendered step list.
 */
export function renderAppPlaybook(
  appId: string,
  bodyMdOverride?: string | null,
): string | null {
  const app = APP_BY_ID[appId];
  if (!app) return null;
  const pack = findSkillByAppId(appId);
  const bodyMd = bodyMdOverride?.trim() || pack?.bodyMd;
  if (bodyMd) {
    return `SELECTED SKILL PLAYBOOK — ${pack?.id ?? app.id} (${app.label}): ${app.oneLiner}\n\n${bodyMd}`;
  }
  if (app.kind === "model") {
    return `MODEL APP ${app.id} (${app.label}, ${app.mode}) — ${app.oneLiner}\nCollect params in ONE turn, then call run_model_app with appId "${app.id}".`;
  }
  const steps = (app.steps ?? [])
    .map((s) => {
      const inputs = s.inputs.length
        ? s.inputs.map((i) => `    - ${renderInput(i)}`).join("\n")
        : "    - (no input — show result/list for review)";
      const notes = s.notes ? `\n    note: ${s.notes}` : "";
      return `  • ${s.id} — ${s.intent}\n${inputs}${notes}`;
    })
    .join("\n");
  return `SELECTED APP PLAYBOOK — ${app.id} (${app.label}): ${app.oneLiner}\nWalk these steps one decision per turn. Skip, reorder, or loop back based on what the user already answered; detour into a model app when an input is missing, then resume.\n${steps}`;
}

/** Human-readable catalog for the agent system prompt. */
export function renderAppCatalogForPrompt(): string {
  const wizard = APP_REGISTRY.filter((a) => a.kind === "wizard");
  const model = APP_REGISTRY.filter((a) => a.kind === "model");
  const fmtWizard = wizard
    .map((a) => {
      const steps = (a.steps ?? [])
        .map((s) => {
          const inputs = s.inputs.length
            ? s.inputs.map((i) => `         - ${renderInput(i)}`).join("\n")
            : "         - (no input — show result/list for review)";
          const notes = s.notes ? `\n         note: ${s.notes}` : "";
          return `      • ${s.id} — ${s.intent}\n${inputs}${notes}`;
        })
        .join("\n");
      return `  ${a.id} (${a.label}) — ${a.oneLiner}\n${steps}`;
    })
    .join("\n\n");
  const fmtModel = model
    .map((a) => `  • ${a.id} (${a.label}, ${a.mode}) — ${a.oneLiner}`)
    .join("\n");
  return `WIZARD APPS — canonical playbook. Walk these steps as gen-UI cards, ONE step per turn. You may skip, reorder, or loop back based on what the user already said; you may also diverge into a MODEL APP mid-flow (e.g. generate a hero still in Nano Banana, then resume) and you may open Character Creator from any "character-picker" input. Always nudge the user forward toward render.\n\n${fmtWizard}\n\nMODEL APPS (single-shot — collect params in ONE card then call run_model_app):\n${fmtModel}`;
}
