/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedBlocksRouteImport } from './routes/_authenticated/blocks'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio.index'
import { Route as ApiPublicRenderTickRouteImport } from './routes/api/public/render-tick'
import { Route as ApiAssetIdRouteImport } from './routes/api/asset.$id'
import { Route as AuthenticatedStudioProjectIdRouteImport } from './routes/_authenticated/studio.$projectId'
import { Route as ApiPublicHooksSweepStalledJobsRouteImport } from './routes/api/public/hooks/sweep-stalled-jobs'
import { Route as ApiPublicHooksPikaPollerRouteImport } from './routes/api/public/hooks/pika-poller'
import { Route as ApiPublicHooksMigrateNeonRouteImport } from './routes/api/public/hooks/migrate-neon'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlocksRoute = AuthenticatedBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicRenderTickRoute = ApiPublicRenderTickRouteImport.update({
  id: '/api/public/render-tick',
  path: '/api/public/render-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetIdRoute = ApiAssetIdRouteImport.update({
  id: '/api/asset/$id',
  path: '/api/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioProjectIdRoute =
  AuthenticatedStudioProjectIdRouteImport.update({
    id: '/studio/$projectId',
    path: '/studio/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksSweepStalledJobsRoute =
  ApiPublicHooksSweepStalledJobsRouteImport.update({
    id: '/api/public/hooks/sweep-stalled-jobs',
    path: '/api/public/hooks/sweep-stalled-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPikaPollerRoute =
  ApiPublicHooksPikaPollerRouteImport.update({
    id: '/api/public/hooks/pika-poller',
    path: '/api/public/hooks/pika-poller',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMigrateNeonRoute =
  ApiPublicHooksMigrateNeonRouteImport.update({
    id: '/api/public/hooks/migrate-neon',
    path: '/api/public/hooks/migrate-neon',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AuthenticatedAccountRoute
  '/blocks': typeof AuthenticatedBlocksRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/public/render-tick': typeof ApiPublicRenderTickRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/api/public/hooks/migrate-neon': typeof ApiPublicHooksMigrateNeonRoute
  '/api/public/hooks/pika-poller': typeof ApiPublicHooksPikaPollerRoute
  '/api/public/hooks/sweep-stalled-jobs': typeof ApiPublicHooksSweepStalledJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AuthenticatedAccountRoute
  '/blocks': typeof AuthenticatedBlocksRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/public/render-tick': typeof ApiPublicRenderTickRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/api/public/hooks/migrate-neon': typeof ApiPublicHooksMigrateNeonRoute
  '/api/public/hooks/pika-poller': typeof ApiPublicHooksPikaPollerRoute
  '/api/public/hooks/sweep-stalled-jobs': typeof ApiPublicHooksSweepStalledJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/blocks': typeof AuthenticatedBlocksRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/public/render-tick': typeof ApiPublicRenderTickRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/api/public/hooks/migrate-neon': typeof ApiPublicHooksMigrateNeonRoute
  '/api/public/hooks/pika-poller': typeof ApiPublicHooksPikaPollerRoute
  '/api/public/hooks/sweep-stalled-jobs': typeof ApiPublicHooksSweepStalledJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/blocks'
    | '/library'
    | '/projects'
    | '/skills'
    | '/api/chat'
    | '/api/transcribe'
    | '/studio/$projectId'
    | '/api/asset/$id'
    | '/api/public/render-tick'
    | '/studio/'
    | '/api/public/hooks/migrate-neon'
    | '/api/public/hooks/pika-poller'
    | '/api/public/hooks/sweep-stalled-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/blocks'
    | '/library'
    | '/projects'
    | '/skills'
    | '/api/chat'
    | '/api/transcribe'
    | '/studio/$projectId'
    | '/api/asset/$id'
    | '/api/public/render-tick'
    | '/studio'
    | '/api/public/hooks/migrate-neon'
    | '/api/public/hooks/pika-poller'
    | '/api/public/hooks/sweep-stalled-jobs'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/_authenticated/account'
    | '/_authenticated/blocks'
    | '/_authenticated/library'
    | '/_authenticated/projects'
    | '/_authenticated/skills'
    | '/api/chat'
    | '/api/transcribe'
    | '/_authenticated/studio/$projectId'
    | '/api/asset/$id'
    | '/api/public/render-tick'
    | '/_authenticated/studio/'
    | '/api/public/hooks/migrate-neon'
    | '/api/public/hooks/pika-poller'
    | '/api/public/hooks/sweep-stalled-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiAssetIdRoute: typeof ApiAssetIdRoute
  ApiPublicRenderTickRoute: typeof ApiPublicRenderTickRoute
  ApiPublicHooksMigrateNeonRoute: typeof ApiPublicHooksMigrateNeonRoute
  ApiPublicHooksPikaPollerRoute: typeof ApiPublicHooksPikaPollerRoute
  ApiPublicHooksSweepStalledJobsRoute: typeof ApiPublicHooksSweepStalledJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blocks': {
      id: '/_authenticated/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof AuthenticatedBlocksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/render-tick': {
      id: '/api/public/render-tick'
      path: '/api/public/render-tick'
      fullPath: '/api/public/render-tick'
      preLoaderRoute: typeof ApiPublicRenderTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$id': {
      id: '/api/asset/$id'
      path: '/api/asset/$id'
      fullPath: '/api/asset/$id'
      preLoaderRoute: typeof ApiAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/$projectId': {
      id: '/_authenticated/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof AuthenticatedStudioProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/sweep-stalled-jobs': {
      id: '/api/public/hooks/sweep-stalled-jobs'
      path: '/api/public/hooks/sweep-stalled-jobs'
      fullPath: '/api/public/hooks/sweep-stalled-jobs'
      preLoaderRoute: typeof ApiPublicHooksSweepStalledJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pika-poller': {
      id: '/api/public/hooks/pika-poller'
      path: '/api/public/hooks/pika-poller'
      fullPath: '/api/public/hooks/pika-poller'
      preLoaderRoute: typeof ApiPublicHooksPikaPollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/migrate-neon': {
      id: '/api/public/hooks/migrate-neon'
      path: '/api/public/hooks/migrate-neon'
      fullPath: '/api/public/hooks/migrate-neon'
      preLoaderRoute: typeof ApiPublicHooksMigrateNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedBlocksRoute: typeof AuthenticatedBlocksRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedStudioProjectIdRoute: typeof AuthenticatedStudioProjectIdRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedBlocksRoute: AuthenticatedBlocksRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedStudioProjectIdRoute: AuthenticatedStudioProjectIdRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiAssetIdRoute: ApiAssetIdRoute,
  ApiPublicRenderTickRoute: ApiPublicRenderTickRoute,
  ApiPublicHooksMigrateNeonRoute: ApiPublicHooksMigrateNeonRoute,
  ApiPublicHooksPikaPollerRoute: ApiPublicHooksPikaPollerRoute,
  ApiPublicHooksSweepStalledJobsRoute: ApiPublicHooksSweepStalledJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
