// This file is automatically generated. Do not edit it directly.
// ---------------------------------------------------------------------------
// LOCAL MODE: Supabase auth is disabled for local development. This middleware
// no longer validates a bearer token — it short-circuits to a fixed
// "local-user" identity backed by the in-memory shim, so every userId-scoped
// server function runs without a hosted database or a real session.
//
// The original token-validating implementation is preserved in git history
// (before the "localhost" branch). Restore it there to re-enable real auth.
// ---------------------------------------------------------------------------
import { createMiddleware } from '@tanstack/react-start'
import type { Database } from './types'
import { createLocalClient } from '@/lib/local-database-shim'

const LOCAL_USER_ID = 'local-user'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    return next({
      context: {
        supabase: createLocalClient<Database>(),
        userId: LOCAL_USER_ID,
        claims: { sub: LOCAL_USER_ID },
      },
    });
  },
);
