// This file is automatically generated. Do not edit it directly.
// ---------------------------------------------------------------------------
// LOCAL MODE: Supabase is disabled for local development. The browser client is
// routed through the in-memory local shim (empty query results + a fake
// "local-user" auth), so the app runs without contacting a hosted database.
//
// The original @supabase/supabase-js client is preserved in git history
// (before the "localhost" branch). Restore it there to re-enable Supabase.
// ---------------------------------------------------------------------------
import type { Database } from './types';
import { createLocalClient } from '@/lib/local-database-shim';

function createSupabaseClient() {
  return createLocalClient<Database>();
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
