// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
// ---------------------------------------------------------------------------
// LOCAL MODE: Supabase is disabled for local development. The admin client is
// routed through the in-memory local shim so server functions run without a
// hosted database (and without needing MY_SUPABASE_SERVICE_ROLE_KEY).
//
// The original service-role client is preserved in git history (before the
// "localhost" branch). Restore it there to re-enable Supabase.
// ---------------------------------------------------------------------------
import type { Database } from './types';
import { createLocalClient } from '@/lib/local-database-shim';

function createSupabaseAdminClient() {
  return createLocalClient<Database>();
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
